// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutNet.Infrastructure.Persistence;

#nullable disable

namespace ScoutNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoutDbContext))]
    [Migration("20260521085850_StoreFullApiFootballData")]
    partial class StoreFullApiFootballData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutNet.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Flag")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CurrentClub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalLeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Injured")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LeagueProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Weight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("LeagueProfileId");

                    b.HasIndex("TeamProfileId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Appearances")
                        .HasColumnType("integer");

                    b.Property<int?>("Assists")
                        .HasColumnType("integer");

                    b.Property<int?>("Blocks")
                        .HasColumnType("integer");

                    b.Property<bool>("Captain")
                        .HasColumnType("boolean");

                    b.Property<int?>("DribblesAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("DribblesPast")
                        .HasColumnType("integer");

                    b.Property<int?>("DribblesSuccess")
                        .HasColumnType("integer");

                    b.Property<int?>("DuelsTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("DuelsWon")
                        .HasColumnType("integer");

                    b.Property<int?>("FoulsCommitted")
                        .HasColumnType("integer");

                    b.Property<int?>("FoulsDrawn")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalsTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("integer");

                    b.Property<int?>("KeyPasses")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Lineups")
                        .HasColumnType("integer");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer");

                    b.Property<int?>("PassAccuracy")
                        .HasColumnType("integer");

                    b.Property<int?>("PassesTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("PenaltyCommitted")
                        .HasColumnType("integer");

                    b.Property<int?>("PenaltyMissed")
                        .HasColumnType("integer");

                    b.Property<int?>("PenaltySaved")
                        .HasColumnType("integer");

                    b.Property<int?>("PenaltyScored")
                        .HasColumnType("integer");

                    b.Property<int?>("PenaltyWon")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int?>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ShotsOn")
                        .HasColumnType("integer");

                    b.Property<int?>("ShotsTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("SubstitutesBench")
                        .HasColumnType("integer");

                    b.Property<int?>("SubstitutesIn")
                        .HasColumnType("integer");

                    b.Property<int?>("SubstitutesOut")
                        .HasColumnType("integer");

                    b.Property<int?>("TacklesTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId");

                    b.HasIndex("PlayerId", "SeasonYear", "LeagueId")
                        .IsUnique();

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.ScoutReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentForm")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Potential")
                        .HasColumnType("integer");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoutId");

                    b.ToTable("ScoutReports");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("ScoutId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Player", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.League", "LeagueProfile")
                        .WithMany()
                        .HasForeignKey("LeagueProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.Team", "TeamProfile")
                        .WithMany()
                        .HasForeignKey("TeamProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeagueProfile");

                    b.Navigation("TeamProfile");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.PlayerStatistics", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.League", "League")
                        .WithMany("Statistics")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("Statistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.Team", "Team")
                        .WithMany("Statistics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.ScoutReport", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("ScoutReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.User", "Scout")
                        .WithMany("ScoutReports")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("Watchlists")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.User", "Scout")
                        .WithMany("Watchlists")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.League", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Player", b =>
                {
                    b.Navigation("ScoutReports");

                    b.Navigation("Statistics");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Team", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.User", b =>
                {
                    b.Navigation("ScoutReports");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
