// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoutNet.Infrastructure.Persistence;

#nullable disable

namespace ScoutNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScoutDbContext))]
    [Migration("20260521084118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoutNet.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ContractUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentClub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "LeagueId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<double>("DribblesSuccessPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("ExpectedGoals")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<double>("InterceptionsPerGame")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<double>("PassAccuracyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer");

                    b.Property<double>("TacklesPerGame")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SeasonYear")
                        .IsUnique();

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.ScoutReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentForm")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Potential")
                        .HasColumnType("integer");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoutId");

                    b.ToTable("ScoutReports");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("ScoutId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.PlayerStatistics", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("Statistics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.ScoutReport", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("ScoutReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.User", "Scout")
                        .WithMany("ScoutReports")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("ScoutNet.Domain.Entities.Player", "Player")
                        .WithMany("Watchlists")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutNet.Domain.Entities.User", "Scout")
                        .WithMany("Watchlists")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.Player", b =>
                {
                    b.Navigation("ScoutReports");

                    b.Navigation("Statistics");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("ScoutNet.Domain.Entities.User", b =>
                {
                    b.Navigation("ScoutReports");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
